package cfb.ict;

public class Transaction {

    static final int SIGNATURE_OR_MESSAGE_OFFSET = 0, SIGNATURE_OR_MESSAGE_LENGTH = 6561;
    static final int EXTRA_DATA_DIGEST_OFFSET = SIGNATURE_OR_MESSAGE_OFFSET + SIGNATURE_OR_MESSAGE_LENGTH, EXTRA_DATA_DIGEST_LENGTH = 243;
    static final int ADDRESS_OFFSET = EXTRA_DATA_DIGEST_OFFSET + EXTRA_DATA_DIGEST_LENGTH, ADDRESS_LENGTH = 243;
    static final int VALUE_OFFSET = ADDRESS_OFFSET + ADDRESS_LENGTH, VALUE_LENGTH = 81;
    static final int ISSUANCE_TIMESTAMP_OFFSET = VALUE_OFFSET + VALUE_LENGTH, ISSUANCE_TIMESTAMP_LENGTH = 27;
    static final int TIMELOCK_LOWER_BOUND_OFFSET = ISSUANCE_TIMESTAMP_OFFSET + ISSUANCE_TIMESTAMP_LENGTH, TIMELOCK_LOWER_BOUND_LENGTH = 27;
    static final int TIMELOCK_UPPER_BOUND_OFFSET = TIMELOCK_LOWER_BOUND_OFFSET + TIMELOCK_LOWER_BOUND_LENGTH, TIMELOCK_UPPER_BOUND_LENGTH = 27;
    static final int BUNDLE_NONCE_OFFSET = TIMELOCK_UPPER_BOUND_OFFSET + TIMELOCK_UPPER_BOUND_LENGTH, BUNDLE_NONCE_LENGTH = 81;
    static final int TRUNK_TRANSACTION_HASH_OFFSET = BUNDLE_NONCE_OFFSET + BUNDLE_NONCE_LENGTH, TRUNK_TRANSACTION_HASH_LENGTH = 243;
    static final int BRANCH_TRANSACTION_HASH_OFFSET = TRUNK_TRANSACTION_HASH_OFFSET + TRUNK_TRANSACTION_HASH_LENGTH, BRANCH_TRANSACTION_HASH_LENGTH = 243;
    static final int TAG_OFFSET = BRANCH_TRANSACTION_HASH_OFFSET + BRANCH_TRANSACTION_HASH_LENGTH, TAG_LENGTH = 81;
    static final int ATTACHMENT_TIMESTAMP_OFFSET = TAG_OFFSET + TAG_LENGTH, ATTACHMENT_TIMESTAMP_LENGTH = 27;
    static final int ATTACHMENT_TIMESTAMP_LOWER_BOUND_OFFSET = ATTACHMENT_TIMESTAMP_OFFSET + ATTACHMENT_TIMESTAMP_LENGTH, ATTACHMENT_TIMESTAMP_LOWER_BOUND_LENGTH = 27;
    static final int ATTACHMENT_TIMESTAMP_UPPER_BOUND_OFFSET = ATTACHMENT_TIMESTAMP_LOWER_BOUND_OFFSET + ATTACHMENT_TIMESTAMP_LOWER_BOUND_LENGTH, ATTACHMENT_TIMESTAMP_UPPER_BOUND_LENGTH = 27;
    static final int TRANSACTION_NONCE_OFFSET = ATTACHMENT_TIMESTAMP_UPPER_BOUND_OFFSET + ATTACHMENT_TIMESTAMP_UPPER_BOUND_LENGTH, TRANSACTION_NONCE_LENGTH = 81;

    static final int TRANSACTION_LENGTH = TRANSACTION_NONCE_OFFSET + TRANSACTION_NONCE_LENGTH;
    static final int BUNDLE_ESSENCE_OFFSET = EXTRA_DATA_DIGEST_OFFSET, BUNDLE_ESSENCE_LENGTH = EXTRA_DATA_DIGEST_LENGTH + ADDRESS_LENGTH + VALUE_LENGTH + ISSUANCE_TIMESTAMP_LENGTH + TIMELOCK_LOWER_BOUND_LENGTH + TIMELOCK_UPPER_BOUND_LENGTH + BUNDLE_NONCE_LENGTH;
}
